### ISSUE TITLE
Some lSDL2 not found error

### ISSUE THREAD

**Issue by VaibhavDS19** [jawline/Mimic#1]
Hi, I am trying to run this on Ubuntu 20.04 on a VM
I get the following error

```
note: /usr/bin/ld: cannot find -lSDL2
error: could not compile `gb_int` due to previous error
```
Please help with this

**Comment by jawline** [comment]
Try 'apt install libsdl2-dev', we build in sdl support even to cli builds
currently.

**Comment by VaibhavDS19** [comment]
It works now, thank you very much.
